low, high = map(int, input().split())

img = input().split()
print(img)

# SELECT BRANCHES.ID AS BRANCH_ID, BRANCHES.NAME AS BRANCH_NAME, COUNT(SELLINGS.CAR_ID) AS COUNT
# FROM EMPLOYEES LEFT JOIN SELLINGS ON EMPLOYEES.ID = SELLINGS.EMPLOYEE_ID 
# LEFT JOIN BRANCHES ON EMPLOYEES.BRANCH_ID = BRANCHES.ID WHERE SELLINGS.CAR_ID = "306" GROUP BY BRANCHES.ID;

